version: '3.8'
services:
  finhub-web-client:
    build: ./client
    environment:
      PORT: 3000
    ports:
     - 3000:3000
    restart: always
    container_name: finhub-client

  finhub-web-server:
    build: ./server
    environment:
      PORT: 3030
    ports:
     - 3030:3030
    restart: always
    container_name: finhub-server

  mongodb:
    image: mongo:5.0
    restart: always
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

volumes:
  mongodata: